/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at http://mozilla.org/MPL/2.0/. */

/** @type MenuData */
const viewMenuData = {
  menu_Toolbars: {},
  view_toolbars_popup_quickFilterBar: {},
  viewToolbarsPopupSpacesToolbar: { checked: true },
  menu_showTaskbar: { checked: true },
  customizeMailToolbars: {},
  menu_MessagePaneLayout: {},
  messagePaneClassic: { checked: true },
  messagePaneWide: {},
  messagePaneVertical: {},
  menu_showFolderPane: { checked: true },
  menu_showFolderPaneCols: { disabled: true },
  menu_showMessage: { checked: true },
  menu_FolderViews: {},
  menu_allFolders: { disabled: true, checked: true },
  menu_smartFolders: {},
  menu_unreadFolders: {},
  menu_favoriteFolders: {},
  menu_recentFolders: {},
  menu_compactMode: { disabled: true },
  menu_uiDensity: {},
  uiDensityCompact: { checked: true },
  uiDensityNormal: {},
  uiDensityTouch: {},
  viewFullZoomMenu: {},
  menu_fullZoomEnlarge: { disabled: true },
  menu_fullZoomReduce: { disabled: true },
  menu_fullZoomReset: { disabled: true },
  menu_fullZoomToggle: { disabled: true },
  menu_uiFontSize: {},
  menu_fontSizeEnlarge: {},
  menu_fontSizeReduce: {},
  menu_fontSizeReset: {},
  calTodayPaneMenu: { hidden: true },
  "calShowTodayPane-2": {},
  calTodayPaneDisplayMiniday: {},
  calTodayPaneDisplayMinimonth: {},
  calTodayPaneDisplayNone: {},
  calCalendarMenu: { hidden: true },
  calChangeViewDay: {},
  calChangeViewWeek: {},
  calChangeViewMultiweek: {},
  calChangeViewMonth: {},
  calCalendarPaneMenu: {},
  calViewCalendarPane: {},
  calTasksViewMinimonth: {},
  calTasksViewCalendarlist: {},
  calCalendarCurrentViewMenu: {},
  calWorkdaysOnlyMenuitem: {},
  calTasksInViewMenuitem: {},
  calShowCompletedInViewMenuItem: {},
  calViewRotated: {},
  calTasksMenu: { hidden: true },
  calTasksViewFilterTasks: {},
  calTasksViewFilterCurrent: {},
  calTasksViewFilterToday: {},
  calTasksViewFilterNext7days: {},
  calTasksViewFilterNotstartedtasks: {},
  calTasksViewFilterOverdue: {},
  calTasksViewFilterCompleted: {},
  calTasksViewFilterOpen: {},
  calTasksViewFilterAll: {},
  viewSortMenu: {},
  sortByDateMenuitem: {},
  sortByReceivedMenuitem: {},
  sortByFlagMenuitem: {},
  sortByOrderReceivedMenuitem: {},
  sortByPriorityMenuitem: {},
  sortByFromMenuitem: {},
  sortByRecipientMenuitem: {},
  sortByCorrespondentMenuitem: {},
  sortBySizeMenuitem: {},
  sortByStatusMenuitem: {},
  sortBySubjectMenuitem: {},
  sortByUnreadMenuitem: {},
  sortByTagsMenuitem: {},
  sortByJunkStatusMenuitem: {},
  sortByAttachmentsMenuitem: {},
  sortAscending: {},
  sortDescending: {},
  sortThreaded: {},
  sortUnthreaded: {},
  groupBySort: {},
  viewMessageViewMenu: { hidden: true },
  viewMessageAll: {},
  viewMessageUnread: {},
  viewMessageNotDeleted: {},
  viewMessageTags: {},
  viewMessageCustomViews: {},
  viewMessageVirtualFolder: {},
  viewMessageCustomize: {},
  viewMessagesMenu: {},
  viewAllMessagesMenuItem: { disabled: true, checked: true },
  viewUnreadMessagesMenuItem: { disabled: true },
  viewThreadsWithUnreadMenuItem: { disabled: true },
  viewWatchedThreadsWithUnreadMenuItem: { disabled: true },
  viewIgnoredThreadsMenuItem: { disabled: true },
  menu_expandAllThreads: { disabled: true },
  collapseAllThreads: { disabled: true },
  viewheadersmenu: {},
  viewallheaders: {},
  viewnormalheaders: { checked: true },
  viewBodyMenu: {},
  bodyAllowHTML: { checked: true },
  bodySanitized: {},
  bodyAsPlaintext: {},
  bodyAllParts: { hidden: true },
  viewFeedSummary: { hidden: true },
  bodyFeedGlobalWebPage: {},
  bodyFeedGlobalSummary: {},
  bodyFeedPerFolderPref: {},
  bodyFeedSummaryAllowHTML: {},
  bodyFeedSummarySanitized: {},
  bodyFeedSummaryAsPlaintext: {},
  viewAttachmentsInlineMenuitem: { checked: true },
  pageSourceMenuItem: { disabled: true },
};
let helper = new MenuTestHelper("menu_View", viewMenuData);

add_setup(async function() {
  document.getElementById("toolbar-menubar").removeAttribute("autohide");
});

add_task(async function test3PaneTab() {
  await helper.testAllItems("mail3PaneTab");
});
