/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIMsgSearchScopeTerm.idl"

[scriptable, uuid(0b09078b-e0cd-440a-afee-01f45808ee74)]
interface nsIMsgSearchAdapter : nsISupports {

    /** Return true if done. */
    boolean search();

    void validateTerms();

    /** Called on the adapter for OnStopRunningUrl() in the search session. */
    void currentUrlDone(in nsresult exitCode);

    void addHit(in nsMsgKey key);
    void addResultElement(in nsIMsgDBHdr aHdr);

    readonly attribute string encoding;

    readonly attribute AString searchCharset;

    /*
     * Clear the saved scope reference. This is used when deleting scope, which is not
     * reference counted in nsMsgSearchSession
     */
    void clearScope();
};
