# Default partner distribution configuration file
# Must be replaced as part of a repack for Enterprise builds

[Global]
id=enterprise-local
version=1.0
about=Mozilla Thunderbird Enterprise Local Build

[Preferences]
enterprise.console.address=https://stormkeeper.sandbox.moz-enterprise.com
