# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.reverse_chunk_deps:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - beetmover-checksums
    - release-beetmover-source-checksums

jobs:
    thunderbird-promote:
        name: post-beetmover-checksums-dummy
        description: Dummy task to deal with max_dependencies
        run-on-projects: []
        shipping-phase: promote
        shipping-product: thunderbird
        worker-type: succeed
        worker:
            implementation: succeed
