[tool.ruff]
line-length = 99
# See https://beta.ruff.rs/docs/rules/ for a full list of rules.
select = [
  "E", "W",    # pycodestyle
  "F",         # pyflakes
  "I",         # isort
]
ignore = [
  # These should be triaged and either fixed or moved to the list below.
  "W605",

  # These are intentionally ignored (not necessarily for good reason).
  "E741",

  # These are handled by black.
  "E1", "E4", "E5", "W2", "W5"
]
exclude = [
  "python/l10n/tb_fluent_migrations"
]
builtins = ["gdb"]

[tool.ruff.per-file-ignores]

[tool.ruff.isort]
known-first-party = [
  "mach",
  "mozboot",
  "mozbuild",
  "mozpack",
  "mozharness",
  "mozlint",
  "mozperftest",
  "mozrelease",
  "mozterm",
  "mozversioncontrol",
  "gecko_taskgraph",
  "buildconfig",
]
known-local-folder = [
  "rocboot",
  "rocbuild",
  "tb_l10n",
  "thirdroc",
  "comm_taskgraph",
]
