/* -*- Mode: IDL; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(088d3dea-4a6a-41ce-b974-5043d00f1798)]
interface nsIAbOutlookInterface : nsISupports
{
  Array<ACString> getFolderURIs(in ACString aURI);
};
