openpgp-key-user-id-label = Account / User ID
openpgp-keygen-title-label =
    .title = Generate OpenPGP Key
openpgp-cancel-key =
    .label = Cancel
    .tooltiptext = Cancel Key Generation
openpgp-key-gen-expiry-title =
    .label = Key expiry
openpgp-key-gen-expire-label = Key expires in
openpgp-key-gen-days-label =
    .label = days
openpgp-key-gen-months-label =
    .label = months
openpgp-key-gen-years-label =
    .label = years
openpgp-key-gen-no-expiry-label =
    .label = Key does not expire
openpgp-key-gen-key-size-label = Key size
openpgp-key-gen-console-label = Key Generation
openpgp-key-gen-key-type-label = Key type
openpgp-key-gen-key-type-rsa =
    .label = RSA
openpgp-key-gen-key-type-ecc =
    .label = ECC (Elliptic Curve)
openpgp-generate-key =
    .label = Generate key
    .tooltiptext = Generates a new OpenPGP compliant key for encryption and/or signing
openpgp-advanced-prefs-button-label =
    .label = Advanced…
openpgp-keygen-desc = <a data-l10n-name="openpgp-keygen-desc-link">NOTE: Key generation may take up to several minutes to complete.</a> Do not exit the application while key generation is in progress. Actively browsing or performing disk-intensive operations during key generation will replenish the 'randomness pool' and speed-up the process. You will be alerted when key generation is completed.

openpgp-key-expiry-label =
    .label = Expiry
openpgp-key-id-label =
    .label = Key ID

openpgp-key-man-title =
    .title = OpenPGP Key Management
openpgp-key-man-generate =
    .label = New Key Pair
    .accesskey = K
openpgp-key-man-gen-revoke =
  .label = Revocation Certificate
  .accesskey = R
openpgp-key-man-ctx-gen-revoke-label =
    .label = Generate & Save Revocation Certificate

openpgp-key-man-file-menu =
    .label = File
    .accesskey = F
openpgp-key-man-edit-menu =
    .label = Edit
    .accesskey = E
openpgp-key-man-view-menu =
    .label = View
    .accesskey = V
openpgp-key-man-generate-menu =
    .label = Generate
    .accesskey = G

openpgp-key-man-import-public-from-file =
    .label = Import Public Key(s) from File
    .accesskey = I
openpgp-key-man-import-secret-from-file =
    .label = Import Secret Keys from File
openpgp-key-man-import-from-clipbrd =
    .label = Import Keys from Clipboard
    .accesskey = I
openpgp-key-man-import-from-url =
    .label = Import Keys from URL
    .accesskey = U
openpgp-key-man-export-to-file =
    .label = Export Keys to File
    .accesskey = E
openpgp-key-man-send-keys =
    .label = Send Public Keys by Email
    .accesskey = S
openpgp-key-man-create-mail =
    .label = Compose Email to Selected Keys
    .accesskey = C
openpgp-key-man-copy-to-clipbrd =
    .label = Copy Public Keys to Clipboard
    .accesskey = C
openpgp-key-man-ctx-expor-to-file-label =
    .label = Export Keys to File
openpgp-key-man-ctx-copy-to-clipbrd-label =
    .label = Copy Public Keys to Clipboard

openpgp-key-man-reload =
    .label = Reload Key Cache
    .accesskey = R
openpgp-key-man-change-expiry =
    .label = Change Expiration Date
    .accesskey = E
openpgp-key-man-del-key =
    .label = Delete Key
    .accesskey = D
openpgp-key-man-revoke-key =
    .label = Revoke Key
    .accesskey = R
openpgp-key-man-key-props =
    .label = Key Properties
    .accesskey = K
openpgp-key-man-show-all-keys =
    .label = Display All Keys by Default
    .accesskey = D
openpgp-key-man-view-photo =
    .label = Photo ID
    .accesskey = P
openpgp-key-man-ctx-view-photo-label =
    .label = View Photo ID
openpgp-key-man-show-invalid-keys =
    .label = Display invalid keys
    .accesskey = D
openpgp-key-man-show-untrusted-keys =
    .label = Display untrusted keys
    .accesskey = U
openpgp-key-man-show-others-keys =
    .label = Display keys from other people
    .accesskey = O
openpgp-key-man-user-id-label =
    .label = Name
openpgp-key-man-fingerprint-label =
    .label = Fingerprint
openpgp-key-man-select-all =
    .label = Select all Keys
    .accesskey = A
openpgp-key-man-empty-tree-tooltip =
    .label = Enter search terms in the box above
openpgp-key-man-nothing-found-tooltip =
    .label = No keys match your search terms
openpgp-key-man-please-wait-tooltip =
    .label = Please wait while keys are being loaded…

openpgp-key-man-filter-label =
    .placeholder = Search for keys


openpgp-key-man-select-all-key =
    .key = A
openpgp-key-man-key-details-key =
    .key = I

openpgp-key-details-title =
    .title = Key Properties
openpgp-key-details-signatures-tab =
    .label = Certifications
openpgp-key-details-structure-tab =
    .label = Structure
openpgp-key-details-uid-certified-col =
    .label = User ID / Certified by
openpgp-key-details-user-id2-label = Alleged Key Owner
openpgp-key-details-id-label =
    .label = ID
openpgp-key-details-key-type-label = Type
openpgp-key-details-key-part-label =
    .label = Key Part
openpgp-key-details-algorithm-label =
    .label = Algorithm
openpgp-key-details-size-label =
    .label = Size
openpgp-key-details-created-label =
    .label = Created
openpgp-key-details-created-header = Created
openpgp-key-details-expiry-label =
    .label = Expiry
openpgp-key-details-expiry-header = Expiry
openpgp-key-details-usage-label =
    .label = Usage
openpgp-key-details-fingerprint-label = Fingerprint
openpgp-key-details-sel-action =
  .label = Select action…
  .accesskey = S
openpgp-key-details-also-known-label = Alleged Alternative Identities of the Key Owner:
openpgp-card-details-close-window-label =
    .buttonlabelaccept = Close
openpgp-acceptance-label =
    .label = Your Acceptance
openpgp-acceptance-rejected-label =
    .label = No, never use this key. (rejected)
openpgp-acceptance-undecided-label =
    .label = Not yet, maybe later. (undecided)
openpgp-acceptance-unverified-label =
    .label = Yes, but I don't know if it is the correct key. (unverified)
openpgp-acceptance-verified-label =
    .label = Yes, I've verified in person this key has the correct fingerprint. (verified)

openpgp-copy-cmd-label =
    .label = Copy
