/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
[scriptable, uuid(3aff0550-87de-4337-9bc1-c84eb5462afe)]
interface nsIPop3Protocol : nsISupports {
  /**
   * Return true if the message header for the UIDL exists.
   */
  boolean checkMessage(in string aUidl);
};
