/* -*- Mode: IDL; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "MailNewsTypes2.idl"

interface nsIMsgNewsFolder;

[scriptable, uuid(043d9dd4-b133-4eb4-a1a8-71abff69b613)]
interface nsINNTPArticleList : nsISupports {
    void initialize(in nsIMsgNewsFolder newsFolder);
    void addArticleKey(in nsMsgKey key);
    void finishAddingArticleKeys();
};

