/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */


/* This is a private interface used exclusively by SMIME. NO ONE outside of extensions/smime
   or the hard coded smime decryption files in mime/src should have any knowledge nor should
   be referring to this interface.
*/

#include "nsISupports.idl"

interface nsIX509Cert;

[scriptable, uuid(25380FA1-E70C-4e82-B0BC-F31C2F41C470)]
interface nsIMsgSMIMEHeaderSink : nsISupports
{
  void signedStatus(in long aNestingLevel,
                    in long aSignatureStatus,
                    in nsIX509Cert aSignerCert,
                    in AUTF8String aMsgNeckoURL,
                    in AUTF8String originMimePartNumber);
  void encryptionStatus(in long aNestingLevel,
                        in long aEncryptionStatus,
                        in nsIX509Cert aReceipientCert,
                        in AUTF8String aMsgNeckoURL,
                        in AUTF8String originMimePartNumber);
  void ignoreStatusFrom(in AUTF8String originMimePartNumber);
  void handleSMimeMessage(in AUTF8String uri);

  /**
   * Although this interface claims it's specific for S/MIME, it was later
   * reused to dispatch OpenPGP status updates, too. The 2 functions below are
   * used for OpenPGP messages.
   * TODO: Clarify this interface, rename it, or split into two separate things.
   */

  void modifyMessageHeaders(in AUTF8String uri,
                            in AUTF8String headerData,
                            in AUTF8String mimePartNumber);
  void updateSecurityStatus(in ACString exitCode,
                            in AUTF8String statusFlags,
                            in AUTF8String extStatusFlags,
                            in AUTF8String keyId,
                            in AUTF8String userId,
                            in AUTF8String sigDetails,
                            in AUTF8String errorMsg,
                            in AUTF8String blockSeparation,
                            in AUTF8String uri,
                            in AUTF8String extraDetails,
                            in AUTF8String mimePartNumber);
};
