/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* This is a private interface used exclusively by SMIME.
   It provides functionality to the JS UI code,
   that is only accessible from C++.
*/

#include "nsISupports.idl"

interface nsIMsgCompFields;
interface nsIX509Cert;

[scriptable, uuid(a54e3c8f-a000-4901-898f-fafb297b1546)]
interface nsISMimeJSHelper : nsISupports
{
  /**
   * Obtains detailed information about the certificate availability
   * status of email recipients.
   *
   * @param compFields - Attributes of the composed message.
   * @param emailAddresses - The list of all recipient email addresses
   * @param certIssuedInfos - If a recipient cert was found, when has it been issued?
   * @param certExpiredInfos - If a recipient cert was found, when will it expire?
   * @param certs - The recipient certificates, which can contain null for not found
   * @param canEncrypt - whether valid certificates have been found for all recipients
   */
  void getRecipientCertsInfo(in nsIMsgCompFields compFields,
                             out Array<AString> emailAddresses,
                             out Array<AString> certIssuedInfos,
                             out Array<AString> certExpiresInfos,
                             out Array<nsIX509Cert> certs,
                             out boolean canEncrypt);

  /**
   * Obtains a list of email addresses where valid email recipient certificates
   * are not yet available.
   *
   * @param compFields - Attributes of the composed message
   * @returns The list of email addresses without valid certs
   */
  Array<AString> getNoCertAddresses(in nsIMsgCompFields compFields);
};
