/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIMsgIdentity.idl"

[scriptable, uuid(00b4569a-077e-4236-b993-980fd82bb948)]
interface nsIMsgCompUtils : nsISupports {
  string mimeMakeSeparator(in string prefix);

  /**
   * Generate a message ID using the provided host.
   *
   * Used when the address for the sender of the message differs from the
   * address of the identity used to send the message.
   *
   * @param string The host to use to generate the message ID.
   *
   * @returns A message ID usable in a Message-ID header, or an empty string
   *          if no message ID could be generated.
   */
  string msgGenerateMessageIdFromHost(in string host);

  /**
   * Generate a message ID using the domain in the email address for the
   * provided identity.
   *
   * Should not be used when the address for the sender of the message differs
   * from the address for the identity, otherwise the resulting message ID might
   * be generated with the wrong domain (use msgGenerateMessageIdFromHost instead
   * in this case).
   *
   * @param nsIMsgIdentity The identity to use to generate the message ID.
   *
   * @returns A message ID usable in a Message-ID header, or an empty string
   *          if no message ID could be generated.
   */
  string msgGenerateMessageIdFromIdentity(in nsIMsgIdentity identity);

  readonly attribute boolean msgMimeConformToStandard;

  /**
   * Detect the text encoding of an input string. This is a wrapper of
   * mozilla::EncodingDetector to be used by JavaScript code. For C++, use
   * MsgDetectCharsetFromFile from nsMsgUtils.cpp instead.
   *
   * @param aContent The string to detect charset.
   *
   * @returns Detected charset.
   */
  ACString detectCharset(in ACString aContent);
};
