/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * An interface for interacting with an SMTP-based nsIMsgOutgoingServer.
 */

[scriptable, uuid(bd1b5e31-0eed-47d4-8158-867a30938e13)]
interface nsISmtpServer : nsISupports {
  /*
   * The server's hostname.
   */
  attribute AUTF8String hostname;

  /*
   * The server's port.
   */
  attribute int32_t port;

  /**
   * The CLIENTID to use for this server (if required).
   *
   * @see https://tools.ietf.org/html/draft-storey-smtp-client-id-05
   */
  attribute AUTF8String clientid;
};
