# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.release_deps:transforms
    - taskgraph.transforms.release_notifications:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - release-balrog-scheduling
    - release-bouncer-aliases
    - release-version-bump
    - release-mark-as-shipped

job-defaults:
    name: notify-release-drivers-ship
    description: Sends email to release-drivers telling release was shipped.
    run-on-projects: []
    shipping-phase: ship
    worker-type: aws-provisioner-v1/gecko-{level}-b-linux
    worker:
        implementation: docker-worker
        os: linux
        docker-image: "ubuntu:16.10"
        max-run-time: 600
        command:
            - /bin/bash
            - -c
            - echo "Dummy task"
    notifications:
        emails:
            by-project:
                comm-(beta|esr60): ["thunderbird-drivers@mozilla.org"]
                try: ["{config[params][owner]}"]
                default: []

jobs:
    thunderbird:
        shipping-product: thunderbird
        notifications:
            subject: "{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]} updates are ready for signoff in Balrog!"
            message: "{task[shipping-product]} {release_config[version]} build{release_config[build_number]}/{config[params][project]} updates are ready for signoff in Balrog!"
