# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Note instantbird.xul contains a modified copy of this file that
# should be kept in sync.
  <commandset id="maincommandset"/>
  <keyset id="mainkeyset"/>
  <menubar id="blistMenubar"/>
  <popupset id="mainPopupSet"/>
