# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: gecko_taskgraph.loader.transform:loader

kind-dependencies:
    - post-balrog-dummy
    - post-beetmover-dummy
    - release-balrog-submit-toplevel
    - release-update-verify-config-next

transforms:
    - gecko_taskgraph.transforms.release:run_on_releases
    - gecko_taskgraph.transforms.release_deps:transforms
    - gecko_taskgraph.transforms.update_verify:transforms
    - gecko_taskgraph.transforms.job:transforms
    - gecko_taskgraph.transforms.task:transforms

job-defaults:
    name: update-verify-next
    run-on-projects: []  # to make sure this never runs as part of CI
    run-on-releases: [esr115]
    shipping-phase: promote
    worker-type: b-linux-gcp
    worker:
        artifacts:
            - name: 'public/build/diff-summary.log'
              path: '/builds/worker/tools/release/updates/diff-summary.log'
              type: file
        docker-image:
            in-tree: "update-verify"
        max-run-time: 7200
        retry-exit-status:
            - 255
        env:
            CHANNEL: "release-localtest-next"
    treeherder:
        symbol: UV(UVnext)
        kind: test
    extra:
        chunks: 12

jobs:
    thunderbird-next-linux64:
        description: linux64 release-next update verify
        shipping-product: thunderbird
        attributes:
            build_platform: linux64-shippable

    thunderbird-next-linux:
        description: linux release-next update verify
        shipping-product: thunderbird
        attributes:
            build_platform: linux-shippable

    thunderbird-next-win64:
        description: win64 release-next update verify
        shipping-product: thunderbird
        attributes:
            build_platform: win64-shippable

    thunderbird-next-win32:
        description: win32 release-next update verify
        shipping-product: thunderbird
        attributes:
            build_platform: win32-shippable

    thunderbird-next-macosx64:
        description: macosx64 release-next update verify
        shipping-product: thunderbird
        attributes:
            build_platform: macosx64-shippable
