# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: comm_taskgraph.loader.reference:loader
base-path: taskcluster/ci

kind-dependencies:
    - fetch

jobs:
    - linux64-binutils
    - linux64-cbindgen
    - linux64-cctools-port
    - linux64-clang
    - linux64-clang-7
    - linux64-clang-macosx-cross
    - linux64-clang-mingw-x64
    - linux64-clang-mingw-x86
    - linux64-gcc
    - linux64-gcc-7
    - linux64-hfsplus
    - linux64-libdmg
    - linux64-llvm-dsymutil
    - linux64-mar-tools
    - linux64-minidump-stackwalk
    - linux64-nasm
    - linux64-node
    - linux64-rust
    - linux64-rust-1.39
    - linux64-rust-1.40
    - linux64-rust-macos
    - linux64-rust-macos-1.40
    - linux64-rust-size
    - linux64-sccache
    - linux64-upx
    - macosx64-minidump-stackwalk
    - macosx64-node
    - mingw32-rust-1.40
    - wasi-sysroot
    - win32-node
    - win32-minidump-stackwalk
    - win64-cbindgen
    - win64-clang-cl
    - win64-dump-syms
    - win64-nasm
    - win64-node
    - win64-rust
    - win64-rust-1.40
    - win64-rust-size
    - win64-sccache
