/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsCharsetConverterManager.h"

#include "../base/src/nsMsgI18N.h"
#include "mozilla/intl/EncodingToLang.h"
#include "nsICharsetConverterManager.h"
#include "nsString.h"

NS_IMPL_ISUPPORTS(nsCharsetConverterManager, nsICharsetConverterManager)

// Email-specific labels. Web-relevant labels are handled by mozilla::Encoding.
// Labels must be lowercase; names must be canonical encoding names or UTF-7.
static constexpr struct {
  nsLiteralCString label;
  nsLiteralCString name;
} kAliases[] = {
    // Added for Solaris ns_langinfo. Unlikely relevant to email.
    // https://bugzilla.mozilla.org/show_bug.cgi?id=77300#c9
    {"646"_ns, "windows-1252"_ns},

    // Aliases for ISO-8859-8-I
    // From the original IBM bidi patch.
    {"iso-8859-8i"_ns, "ISO-8859-8-I"_ns},

    // ISO 8859 series with underscore for JavaMail
    // compat.
    // https://bugzilla.mozilla.org/show_bug.cgi?id=820767
    {"iso8859_1"_ns, "windows-1252"_ns},
    {"iso8859_2"_ns, "ISO-8859-2"_ns},
    {"iso8859_3"_ns, "ISO-8859-3"_ns},
    {"iso8859_4"_ns, "ISO-8859-4"_ns},
    {"iso8859_5"_ns, "ISO-8859-5"_ns},
    {"iso8859_6"_ns, "ISO-8859-6"_ns},
    {"iso8859_7"_ns, "ISO-8859-7"_ns},
    // Unclear if 8 with underscore was visual or not
    {"iso8859_9"_ns, "windows-1254"_ns},
    // No evidence of 10 occurring with underscore
    // 11 is tis620
    // 12 does not exist
    {"iso8859_13"_ns, "ISO-8859-13"_ns},
    // No evidence of 14 occurring with underscore
    {"iso8859_15"_ns, "ISO-8859-15"_ns},
    // No evidence of 16 occurring with underscore

    {"koi8r"_ns, "KOI8-R"_ns},

    // Code pages shared by DOS and Windows with ms prefix.
    // Evidence of this pattern in the wild:
    // https://bugzilla.mozilla.org/show_bug.cgi?id=1120813
    // Plausible cause: JavaMail
    // The ms prefix as used by Sun is not relevant to windows-125x series
    {"ms874"_ns, "windows-874"_ns},
    // ms932 was added to the Encoding Standard as one-off Thunderbird request
    // MS936 shows up at
    // https://www.iana.org/assignments/character-sets/character-sets.xhtml
    {"ms936"_ns, "GBK"_ns},
    {"ms949"_ns, "EUC-KR"_ns},
    {"ms950"_ns, "Big5"_ns},
    {"ms950_hkscs"_ns, "Big5"_ns},

    // Underscore versions of Unix CJK encodings.
    // No evidence of these in the wild, but these could plausibly
    // occur for the same reason as the above two groups.
    {"euc_cn"_ns, "GBK"_ns},
    {"euc_kr"_ns, "EUC-KR"_ns},
    {"euc_jp"_ns, "EUC-JP"_ns},
    {"big5_hkscs"_ns, "Big5"_ns},

    // Code pages shared by DOS and Windows with cp prefix
    // cp125x series are in the Encoding Standard
    // Evidence of the pattern in the wild:
    // https://bugzilla.mozilla.org/show_bug.cgi?id=1511950
    // https://bugzilla.mozilla.org/show_bug.cgi?id=542823
    // https://bugzilla.mozilla.org/show_bug.cgi?id=1217161
    {"cp874"_ns, "windows-874"_ns},
    {"cp932"_ns, "Shift_JIS"_ns},
    // CP936 shows up at
    // https://www.iana.org/assignments/character-sets/character-sets.xhtml
    {"cp936"_ns, "GBK"_ns},
    {"cp949"_ns, "EUC-KR"_ns},
    {"cp950"_ns, "Big5"_ns},

    // Aliases for ISO-2022-JP
    // The following are really not aliases ISO-2022-JP, but sharing the same
    // decoder
    // Kept mainly for compat with old Apple Mail.
    {"iso-2022-jp-2"_ns, "ISO-2022-JP"_ns},
    {"csiso2022jp2"_ns, "ISO-2022-JP"_ns},
    // A Google search suggests the variant without hyphens has been used with
    // JavaMail.
    {"iso2022jp"_ns, "ISO-2022-JP"_ns},

    // Aliases for Big5
    // Added in patch that generally meant to support emails sent by
    // dtmail on Sun Solaris
    // https://bugzilla.mozilla.org/show_bug.cgi?id=146287
    {"zh_tw-big5"_ns, "Big5"_ns},

    // Aliases for EUC-KR
    // Added for Solaris ns_langinfo. Unlikely relevant to email.
    // https://bugzilla.mozilla.org/show_bug.cgi?id=82075
    {"5601"_ns, "EUC-KR"_ns},
    // https://bugzilla.mozilla.org/show_bug.cgi?id=234958
    {"x-windows-949"_ns, "EUC-KR"_ns},

    // Aliases for windows-874
    // Added originally for nl_langinfo reasons but could plausibly be sent
    // by JavaMail.
    // https://bugzilla.mozilla.org/show_bug.cgi?id=101295
    {"tis620"_ns, "windows-874"_ns},

    // Aliases for IBM866
    // This alias may have been made up by accident and may
    // not be relevant to real-world email.
    // https://bugzilla.mozilla.org/show_bug.cgi?id=77588
    {"cp-866"_ns, "IBM866"_ns},

    // Aliases for UTF-7
    {"utf-7"_ns, "UTF-7"_ns},
    // The below 4 aliases were not in Thunderbird 60, and there were
    // no complaints.
    // This alias appears to have been generated by the email part
    // of the Netscape 4.0 suite per http://jkorpela.fi/chars.html
    {"x-unicode-2-0-utf-7"_ns, "UTF-7"_ns},
    // This appears to be just a made-up non-x version of the above
    // (checked in without bug number).
    {"unicode-2-0-utf-7"_ns, "UTF-7"_ns},
    // The two aliases below show up at
    // https://www.iana.org/assignments/character-sets/character-sets.xhtml
    {"unicode-1-1-utf-7"_ns, "UTF-7"_ns},
    {"csunicode11utf7"_ns, "UTF-7"_ns},

    // The below aliases were not in Thunderbird 60, and there were
    // no complaints.
    // These aliases show up at
    // https://www.iana.org/assignments/character-sets/character-sets.xhtml
    {"csunicode"_ns, "UTF-16BE"_ns},
    {"csunicode11"_ns, "UTF-16BE"_ns},
    {"iso-10646-ucs-basic"_ns, "UTF-16BE"_ns},
    {"csunicodeascii"_ns, "UTF-16BE"_ns},
    {"iso-10646-unicode-latin1"_ns, "UTF-16BE"_ns},
    {"csunicodelatin1"_ns, "UTF-16BE"_ns},
    {"iso-10646"_ns, "UTF-16BE"_ns},
    {"iso-10646-j-1"_ns, "UTF-16BE"_ns},
    {"iso-10646-ucs-2"_ns, "UTF-16BE"_ns},
    // Netscape aliases checked in without bug number.
    // Possibly meant to be Netscape-private.
    {"x-iso-10646-ucs-2-be"_ns, "UTF-16BE"_ns},
    {"x-iso-10646-ucs-2-le"_ns, "UTF-16LE"_ns},

    // Shows up at
    // https://www.iana.org/assignments/character-sets/character-sets.xhtml
    // https://bugzilla.mozilla.org/show_bug.cgi?id=651113
    {"windows-936"_ns, "GBK"_ns},

    // Added for Solaris ns_langinfo(). Unlikely to be relevant to email.
    // https://bugzilla.mozilla.org/show_bug.cgi?id=82075
    {"ansi-1251"_ns, "windows-1251"_ns},
};

NS_IMETHODIMP
nsCharsetConverterManager::GetCharsetAlias(const char* charset,
                                           nsACString& result) {
  NS_ENSURE_ARG_POINTER(charset);
  nsAutoCString label(charset);
  if (label.IsEmpty()) return NS_ERROR_NULL_POINTER;
  ToLowerCase(label);

  const mozilla::Encoding* encoding = mozilla::Encoding::ForLabel(label);
  if (encoding) {
    if (encoding == REPLACEMENT_ENCODING) {
      return NS_ERROR_UCONV_NOCONV;
    }
    encoding->Name(result);
    return NS_OK;
  }

  for (const auto& alias : kAliases) {
    if (label.Equals(alias.label)) {
      result = alias.name;
      return NS_OK;
    }
  }

  result.Truncate();
  return NS_ERROR_NOT_AVAILABLE;
}

NS_IMETHODIMP
nsCharsetConverterManager::GetCharsetLangGroup(const char* aCharset,
                                               nsACString& aResult) {
  // Resolve a possible charset alias first.
  nsAutoCString label;
  nsresult rv = GetCharsetAlias(aCharset, label);
  NS_ENSURE_SUCCESS(rv, rv);

  // There is no UTF-7 mozilla::Encoding, so we do this replacement which
  // yields the same result.
  if (label.Equals("UTF-7")) {
    label = "utf-8";
  }

  const mozilla::Encoding* encoding = mozilla::Encoding::ForLabel(label);
  if (!encoding) {
    return NS_ERROR_NOT_AVAILABLE;
  }

  // Unfortunately, the Mozilla lookup function returns the current
  // locale for these encodings, so we check these directly.
  const mozilla::NotNull<const mozilla::Encoding*>* xUnicodeEncodings[] = {
      &UTF_8_ENCODING, &UTF_16BE_ENCODING, &UTF_16LE_ENCODING,
      &REPLACEMENT_ENCODING, &X_USER_DEFINED_ENCODING};
  for (auto& xUnicodeEncoding : xUnicodeEncodings) {
    if (*xUnicodeEncoding == encoding) {
      aResult = "x-unicode";
      return NS_OK;
    }
  }
  nsAtom* lang = mozilla::intl::EncodingToLang::Lookup(WrapNotNull(encoding));
  lang->ToUTF8String(aResult);
  return NS_OK;
}

NS_IMETHODIMP
nsCharsetConverterManager::IsMultiByteCharset(const char* aCharset,
                                              bool* aResult) {
  if (!aCharset) {
    *aResult = false;
    return NS_OK;
  }
  nsAutoCString label(aCharset);
  ToLowerCase(label);
  const mozilla::Encoding* encoding = mozilla::Encoding::ForLabel(label);
  if (!encoding) {
    // mozilla::Encoding doesn't know about UTF-7, which is also multi byte.
    *aResult = label.Equals("utf-7");
    return NS_OK;
  }
  *aResult = !encoding->IsSingleByte();
  return NS_OK;
}

NS_IMETHODIMP
nsCharsetConverterManager::Utf7ToUnicode(const nsACString& aSrc,
                                         nsAString& aDest) {
  return CopyUTF7toUTF16(aSrc, aDest);
}

NS_IMETHODIMP
nsCharsetConverterManager::Mutf7ToUnicode(const nsACString& aSrc,
                                          nsAString& aDest) {
  return CopyMUTF7toUTF16(aSrc, aDest);
}

NS_IMETHODIMP
nsCharsetConverterManager::UnicodeToMutf7(const nsAString& aSrc,
                                          nsACString& aDest) {
  return CopyUTF16toMUTF7(aSrc, aDest);
}
